name: mcq_scanner_ws
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - kivy=2.3.1
  - requests=2.32.5
  - beautifulsoup4=4.14.2
  - pillow=8.4.0
  - setuptools
  - certifi=2025.10.5
  - charset-normalizer=3.4.4
  - urllib3=2.5.0
  - idna=3.11
  - soupsieve=2.8
  - protobuf=5.29.5
  - typing-extensions=4.15.0

  - pip:
      - kivymd==1.2.0
      - googlesearch-python==1.3.0
      - google-generativeai==0.8.5
      - python_dotenv==1.2.1